# Book settings
title: "DHIS2API"
author: "Charlie Zhang"
only_build_toc_files: false

repository:
  url: https://github.com/ccxzhang/dhis2api
  branch: main

# HTML-specific settings
html:
  home_page_in_navbar: false
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://ccxzhang.github.io/dhis2api  
  favicon: "images/favicon.ico"

# Execution settings
execute:
  execute_notebooks: off

# Sphinx settings
sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinxcontrib.apidoc

  config:
    autodoc_typehints: "description"
    apidoc_module_dir: "../dhis2api"
    apidoc_output_dir: "api"
    apidoc_excluded_paths:
      - "tests"
    apidoc_separate_modules: true
