name: docs
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"
      
      - name: Install Poetry & Dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --extras "docs" --no-interaction
      
      - name: Generate API Docs (using sphinx-apidoc)
        run: |
          sphinx-apidoc -o docs/api dhis2api
          
      - name: Build Jupyter Book
        run: |
          jupyter-book build docs --path-output _build/html
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "_build/html"

  deploy-book:
    needs: build-book
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
