name: docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"

      - name: Install Poetry and Dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --extras "docs" --no-interaction

      - name: Generate API Docs (with sphinx-apidoc)
        run: |
          sphinx-apidoc -o docs/api dhis2api

      - name: Build Jupyter Book
        run: |
          jupyter-book build docs

      - name: Deploy built site to gh-pages branch 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages
